
datasource:
  writer:
    url: jdbc:mysql://localhost:3316/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
  reader:
    url: jdbc:mysql://localhost:3326/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
logging:
  level:
    com: info
