spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
#    username: root
#    password: 111111
  profiles:
    active:
      - homework02
logging:
  level:
    com: info

---
spring:
  profiles: homework02
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 111111

---
spring:
  profiles: homework09
datasource:
  writer:
    url: jdbc:mysql://localhost:3316/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
  reader:
    url: jdbc:mysql://localhost:3326/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root

---
spring:
  profiles: homework10
  datasource:
      url: jdbc:mysql://localhost:3307/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      username: root
      password: 111111