#logging:
#  level:
#    com: info
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3307/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
#    username: root
#    password: 111111
mybatis:
  type-aliases-package: com.github.ck_oio.javaatcjobs.shopping.shoppingdao.model
