spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: 111111


